### ISSUE TITLE
too many files open

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/ypm#8]
```
E20200520-14:44:29.169(2) (webapp_server.js:533) Error serving static file Error: EMFILE: too many open files, open '/home/zeno/.software/ypm/.meteor/local/build/programs/web.browser/merged-stylesheets.css'
E20200520-14:44:29.206(2) (webapp_server.js:533) Error serving static file Error: EMFILE: too many open files, open '/home/zeno/.software/ypm/.meteor/local/build/programs/web.browser/packages/meteor.js'
E20200520-14:44:29.240(2) (webapp_server.js:533) Error serving static file Error: EMFILE: too many open files, open '/home/zeno/.software/ypm/.meteor/local/build/programs/web.browser/packages/ecmascript.js'
```

**Comment by zdavatz** [comment]
```
I20200629-14:24:00.003(2) (littledata_synced-cron.js:87) SyncedCron: Exception "CronParser" Error: Error: EMFILE: too many open files, open '/home/zeno/.software/ypm/.meteor/local/build/programs/server/assets/app/feeds.txt' [app-readAssetsErr]
    at Object.app.readAssets (server/app/app.js:30:15)
    at Object.job (server/main.js:52:20)
    at packages/littledata_synced-cron.js:251:26
    at scheduleTimeout (packages/littledata_synced-cron.js:304:9)
    at packages/littledata_synced-cron.js:356:42
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/meteor.js:550:25
    at runWithEnvironment (packages/meteor.js:1286:24)
Unexpected mongo exit code null. Restarting.
```
